insert into category values (0, 'hard_fact')
insert into category values (1, 'lifestyle')
insert into category values (2, 'introversion')
insert into category values (3, 'passion')

insert into question values (0, 'What is your gender?', 0)
insert into question values (1, 'How important is the gender of your partner?', 0)
insert into question values (2, 'How important is the age of your partner to you?', 0)
insert into question values (3, 'Do any children under the age of 18 live with you?', 0)
insert into question values (4, 'How should your potential partner respond to this question?', 1)
insert into question values (5, 'Could you imagine having children with your potential partner?', 1)
insert into question values (6, 'How should your potential partner respond to this question?', 1)
insert into question values (7, 'What is your marital status?', 0)
insert into question values (8, 'How often do your drink alcohol?', 1)
insert into question values (9, 'How often do you smoke?', 1)
insert into question values (10, 'What is your attitude towards drugs?', 1)
insert into question values (11,'You are looking for...', 1)
insert into question values (12,'Would you like to get married?', 1)
insert into question values (13, 'What is your ideal living arrangement?', 1)
insert into question values (14, 'Do you enjoy spending time alone?', 2)
insert into question values (15, 'When you''re alone, do you get lonely quickly?', 2)
insert into question values (16, 'Do you enjoy going on holiday by yourself?', 2)
insert into question values (17, 'I consciously take "me time"', 2)
insert into question values (18, 'Should one keep little secrets from one''s partner?', 2)
insert into question values (19, 'How often do you think about sex?', 3)
insert into question values (20, 'If you were alone on a desert island, how long would you last before pleasuring yourself?', 3)
insert into question values (21, 'How often would you like to have sex with your prospective partner?', 3)
insert into question values (22, 'Do you like trying out new things in bed and experimenting?', 3)
insert into question values (23, 'I can enjoy sex without love', 3)
insert into question values (24, 'For me, a stable relationship is a prerequisite for really good sex', 3)

insert into option values(0, 'male')
insert into option values(1, 'female')
insert into option values(2, 'other')
insert into option values(3, 'not important')
insert into option values(4, 'important')
insert into option values(5, 'very important')
insert into option values(6, 'yes')
insert into option values(7, 'sometimes')
insert into option values(8, 'no')
insert into option values(9, 'yes')
insert into option values(10, 'maybe')
insert into option values(11, 'no')
insert into option values(12, 'never married')
insert into option values(13, 'separated')
insert into option values(14, 'divorced')
insert into option values(15, 'widowed')
insert into option values(16, 'never')
insert into option values(17, 'once or twice a year')
insert into option values(18, 'once or twice a month')
insert into option values(19, 'once or twice a week')
insert into option values(20, 'I''m drinking my 3rd mojito now, and it''s only 11am')
insert into option values(21, 'never')
insert into option values(22, 'once or twice a year')
insert into option values(23, 'socially')
insert into option values(24, 'frequently')
insert into option values(25, 'I''m completely opposed')
insert into option values(26, 'I''ve been know to dabble')
insert into option values(27, 'drugs enrich my life')
insert into option values(28, 'friendship')
insert into option values(29, 'a hot date')
insert into option values(30, 'an affair')
insert into option values(31, 'a short-term relationship')
insert into option values(32, 'a long-term relationship')
insert into option values(33, 'yes')
insert into option values(34, 'probably')
insert into option values(35, 'eventually')
insert into option values(36, 'no')
insert into option values(37, 'cohabitation')
insert into option values(38, 'separate flat / room in the same building')
insert into option values(39, 'separate flats in the same area')
insert into option values(40, 'weekend-relationship')
insert into option values(41, 'long distance relationship')
insert into option values(42, 'most of the time')
insert into option values(43, 'often')
insert into option values(44, 'sometimes')
insert into option values(45, 'rarely')
insert into option values(46, 'not at all')
insert into option values(47, 'a few times a day')
insert into option values(48, 'daily')
insert into option values(49, 'a few times a week')
insert into option values(50, 'a few times a month')
insert into option values(51, 'rarely')
insert into option values(52, 'less than a day')
insert into option values(53, 'one day')
insert into option values(54, 'one week')
insert into option values(55, 'one month')
insert into option values(56, 'I''d never do something like that')
insert into option values(57, 'every day')
insert into option values(58, 'a few times a week')
insert into option values(59, 'once a week')
insert into option values(60, 'every two weeks')
insert into option values(61, 'infrequently')
insert into option values(62, 'rarely')
insert into option values(63, 'Yes, definitely!')
insert into option values(64, 'Now and then - why not?')
insert into option values(65, 'I''d give it a try')
insert into option values(66, 'I don''t know')
insert into option values(67, 'Absolutely not')
insert into option values(68, 'always')
insert into option values(69, 'often')
insert into option values(70, 'often')
insert into option values(71, 'sometimes')
insert into option values(72, 'rarely')
insert into option values(73, 'never')

insert into question_options values(0, 0)
insert into question_options values(0, 1)
insert into question_options values(0, 2)
insert into question_options values(1, 3)
insert into question_options values(1, 4)
insert into question_options values(1, 5)
insert into question_options values(2, 3)
insert into question_options values(2, 4)
insert into question_options values(2, 5)
insert into question_options values(3, 6)
insert into question_options values(3, 7)
insert into question_options values(3, 8)
insert into question_options values(4, 6)
insert into question_options values(4, 7)
insert into question_options values(4, 8)
insert into question_options values(5, 9)
insert into question_options values(5, 10)
insert into question_options values(5, 11)
insert into question_options values(6, 9)
insert into question_options values(6, 10)
insert into question_options values(6, 11)
insert into question_options values(7, 12)
insert into question_options values(7, 13)
insert into question_options values(7, 14)
insert into question_options values(7, 15)
insert into question_options values(8, 16)
insert into question_options values(8, 17)
insert into question_options values(8, 18)
insert into question_options values(8, 19)
insert into question_options values(8, 20)
insert into question_options values(9, 21)
insert into question_options values(9, 22)
insert into question_options values(9, 23)
insert into question_options values(9, 24)
insert into question_options values(10, 25)
insert into question_options values(10, 26)
insert into question_options values(10, 27)
insert into question_options values(11, 28)
insert into question_options values(11, 29)
insert into question_options values(11, 30)
insert into question_options values(11, 31)
insert into question_options values(11, 32)
insert into question_options values(12, 33)
insert into question_options values(12, 34)
insert into question_options values(12, 35)
insert into question_options values(12, 36)
insert into question_options values(13, 37)
insert into question_options values(13, 38)
insert into question_options values(13, 39)
insert into question_options values(13, 40)
insert into question_options values(13, 41)
insert into question_options values(14, 42)
insert into question_options values(14, 43)
insert into question_options values(14, 44)
insert into question_options values(14, 45)
insert into question_options values(14, 46)
insert into question_options values(15, 42)
insert into question_options values(15, 43)
insert into question_options values(15, 44)
insert into question_options values(15, 45)
insert into question_options values(15, 46)
insert into question_options values(16, 42)
insert into question_options values(16, 43)
insert into question_options values(16, 44)
insert into question_options values(16, 45)
insert into question_options values(16, 46)
insert into question_options values(17, 42)
insert into question_options values(17, 43)
insert into question_options values(17, 44)
insert into question_options values(17, 45)
insert into question_options values(17, 46)
insert into question_options values(18, 42)
insert into question_options values(18, 43)
insert into question_options values(18, 44)
insert into question_options values(18, 45)
insert into question_options values(18, 46)
insert into question_options values(19, 47)
insert into question_options values(19, 48)
insert into question_options values(19, 49)
insert into question_options values(19, 50)
insert into question_options values(19, 51)
insert into question_options values(20, 52)
insert into question_options values(20, 53)
insert into question_options values(20, 54)
insert into question_options values(20, 55)
insert into question_options values(20, 56)
insert into question_options values(21, 57)
insert into question_options values(21, 58)
insert into question_options values(21, 59)
insert into question_options values(21, 60)
insert into question_options values(21, 61)
insert into question_options values(21, 62)
insert into question_options values(22, 63)
insert into question_options values(22, 64)
insert into question_options values(22, 65)
insert into question_options values(22, 66)
insert into question_options values(22, 67)
insert into question_options values(23, 68)
insert into question_options values(23, 69)
insert into question_options values(23, 70)
insert into question_options values(23, 71)
insert into question_options values(23, 72)
insert into question_options values(23, 73)
insert into question_options values(24, 68)
insert into question_options values(24, 69)
insert into question_options values(24, 70)
insert into question_options values(24, 71)
insert into question_options values(24, 72)
insert into question_options values(24, 73)

